set_property PACKAGE_PIN U9 [get_ports x[1]]
set_property IOSTANDARD LVCMOS33 [get_ports x[1]]
set_property PACKAGE_PIN U8 [get_ports x[0]]
set_property IOSTANDARD LVCMOS33 [get_ports x[0]]
set_property PACKAGE_PIN R7 [get_ports y[1]]
set_property IOSTANDARD LVCMOS33 [get_ports y[1]]
set_property PACKAGE_PIN R6 [get_ports y[0]]
set_property IOSTANDARD LVCMOS33 [get_ports y[0]]
set_property PACKAGE_PIN V5 [get_ports s]
set_property IOSTANDARD LVCMOS33 [get_ports s]

set_property PACKAGE_PIN T8 [get_ports m[1]]
set_property IOSTANDARD LVCMOS33 [get_ports m[1]]
set_property PACKAGE_PIN V9 [get_ports m[0]]
set_property IOSTANDARD LVCMOS33 [get_ports m[0]]

