# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: //state-opera.ecs.vuw.ac.nz/chinhau/Desktop/lab7/Wavematic/lab7B/lab7B.srcs/constrs_1/imports/constr/Nexys4DDR_Master.xdc

# Block Designs: bd/Lab6_1/Lab6_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1 || ORIG_REF_NAME==Lab6_1} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_microblaze_0_0/Lab6_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_microblaze_0_0 || ORIG_REF_NAME==Lab6_1_microblaze_0_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_clk_wiz_0_0/Lab6_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_clk_wiz_0_0 || ORIG_REF_NAME==Lab6_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_axi_gpio_0_0/Lab6_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_axi_gpio_0_0 || ORIG_REF_NAME==Lab6_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_axi_uartlite_0_0/Lab6_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_axi_uartlite_0_0 || ORIG_REF_NAME==Lab6_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_dlmb_v10_0/Lab6_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_dlmb_v10_0 || ORIG_REF_NAME==Lab6_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_ilmb_v10_0/Lab6_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_ilmb_v10_0 || ORIG_REF_NAME==Lab6_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_dlmb_bram_if_cntlr_0/Lab6_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab6_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_ilmb_bram_if_cntlr_0/Lab6_1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab6_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_lmb_bram_0/Lab6_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_lmb_bram_0 || ORIG_REF_NAME==Lab6_1_lmb_bram_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_mdm_1_0/Lab6_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_mdm_1_0 || ORIG_REF_NAME==Lab6_1_mdm_1_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_rst_clk_wiz_0_100M_0/Lab6_1_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Lab6_1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_xbar_0/Lab6_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_xbar_0 || ORIG_REF_NAME==Lab6_1_xbar_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_microblaze_0_axi_periph_0/Lab6_1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Lab6_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_PWMAudio_0_0/Lab6_1_PWMAudio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_PWMAudio_0_0 || ORIG_REF_NAME==Lab6_1_PWMAudio_0_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_PWMAudio_0_0/src/dist_mem_gen_0/dist_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# IP: bd/Lab6_1/ip/Lab6_1_axi_gpio_1_2/Lab6_1_axi_gpio_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_1_axi_gpio_1_2 || ORIG_REF_NAME==Lab6_1_axi_gpio_1_2} -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_microblaze_0_0/Lab6_1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_microblaze_0_0 || ORIG_REF_NAME==Lab6_1_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_microblaze_0_0/Lab6_1_microblaze_0_0_ooc_debug.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_clk_wiz_0_0/Lab6_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_clk_wiz_0_0 || ORIG_REF_NAME==Lab6_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_clk_wiz_0_0/Lab6_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_clk_wiz_0_0 || ORIG_REF_NAME==Lab6_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_clk_wiz_0_0/Lab6_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_axi_gpio_0_0/Lab6_1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_axi_gpio_0_0 || ORIG_REF_NAME==Lab6_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_axi_gpio_0_0/Lab6_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_axi_gpio_0_0/Lab6_1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_axi_gpio_0_0 || ORIG_REF_NAME==Lab6_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_axi_uartlite_0_0/Lab6_1_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_axi_uartlite_0_0 || ORIG_REF_NAME==Lab6_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_axi_uartlite_0_0/Lab6_1_axi_uartlite_0_0_ooc.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_axi_uartlite_0_0/Lab6_1_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_axi_uartlite_0_0 || ORIG_REF_NAME==Lab6_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_lmb_bram_0/Lab6_1_lmb_bram_0_ooc.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_mdm_1_0/Lab6_1_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_mdm_1_0 || ORIG_REF_NAME==Lab6_1_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_mdm_1_0/Lab6_1_mdm_1_0_ooc_trace.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_rst_clk_wiz_0_100M_0/Lab6_1_rst_clk_wiz_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Lab6_1_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_rst_clk_wiz_0_100M_0/Lab6_1_rst_clk_wiz_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Lab6_1_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_PWMAudio_0_0/src/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_axi_gpio_1_2/Lab6_1_axi_gpio_1_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_axi_gpio_1_2 || ORIG_REF_NAME==Lab6_1_axi_gpio_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/ip/Lab6_1_axi_gpio_1_2/Lab6_1_axi_gpio_1_2_ooc.xdc

# XDC: bd/Lab6_1/ip/Lab6_1_axi_gpio_1_2/Lab6_1_axi_gpio_1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab6_1_axi_gpio_1_2 || ORIG_REF_NAME==Lab6_1_axi_gpio_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Lab6_1/Lab6_1_ooc.xdc
