# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/EEEN402/lab 7/lab_7_noisy/lab_7_noisy.srcs/sources_1/ip/PWMAudio_0/PWMAudio_0.xci
# IP: The module: 'PWMAudio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: h:/EEEN402/lab 7/lab_7_noisy/lab_7_noisy.srcs/sources_1/ip/PWMAudio_0/src/dist_mem_gen_0/dist_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: h:/EEEN402/lab 7/lab_7_noisy/lab_7_noisy.srcs/sources_1/ip/PWMAudio_0/src/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc

# IP: h:/EEEN402/lab 7/lab_7_noisy/lab_7_noisy.srcs/sources_1/ip/PWMAudio_0/PWMAudio_0.xci
# IP: The module: 'PWMAudio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: h:/EEEN402/lab 7/lab_7_noisy/lab_7_noisy.srcs/sources_1/ip/PWMAudio_0/src/dist_mem_gen_0/dist_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: h:/EEEN402/lab 7/lab_7_noisy/lab_7_noisy.srcs/sources_1/ip/PWMAudio_0/src/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
